version: '3.8'

services:
  web:
    build: .
    ports:
      - "50001:50001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 